<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>a33d0186-220d-4018-8979-82ca375180fb</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
		<DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
		<PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cycling.Rider.Tracking.Infrastructure\Cycling.Rider.Tracking.Infrastructure.csproj" />
	</ItemGroup>

</Project>
