<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Cycling.Rider.Tracking.SharedKernel\Cycling.Rider.Tracking.SharedKernel.csproj" />
    <ProjectReference Include="..\Cycling.Rider.Tracking.Domain\Cycling.Rider.Tracking.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Outbox\" />
  </ItemGroup>

</Project>
