// <auto-generated />
using System;
using Cycling.Rider.Tracking.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cycling.Rider.Tracking.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260604212044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cycling.Rider.Tracking.Domain.Rides.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("RideData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ride_data");

                    b.Property<DateTimeOffset>("RideDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ride_date");

                    b.HasKey("Id")
                        .HasName("pk_ride");

                    b.ToTable("ride", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
